package main

const ardanContributors = `[
  {
    "login": "ardan-bkennedy",
    "id": 2280005,
    "avatar_url": "https://avatars3.githubusercontent.com/u/2280005?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ardan-bkennedy",
    "html_url": "https://github.com/ardan-bkennedy",
    "followers_url": "https://api.github.com/users/ardan-bkennedy/followers",
    "following_url": "https://api.github.com/users/ardan-bkennedy/following{/other_user}",
    "gists_url": "https://api.github.com/users/ardan-bkennedy/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ardan-bkennedy/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ardan-bkennedy/subscriptions",
    "organizations_url": "https://api.github.com/users/ardan-bkennedy/orgs",
    "repos_url": "https://api.github.com/users/ardan-bkennedy/repos",
    "events_url": "https://api.github.com/users/ardan-bkennedy/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ardan-bkennedy/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 700
  },
  {
    "login": "dwhitena",
    "id": 4524535,
    "avatar_url": "https://avatars0.githubusercontent.com/u/4524535?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dwhitena",
    "html_url": "https://github.com/dwhitena",
    "followers_url": "https://api.github.com/users/dwhitena/followers",
    "following_url": "https://api.github.com/users/dwhitena/following{/other_user}",
    "gists_url": "https://api.github.com/users/dwhitena/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dwhitena/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dwhitena/subscriptions",
    "organizations_url": "https://api.github.com/users/dwhitena/orgs",
    "repos_url": "https://api.github.com/users/dwhitena/repos",
    "events_url": "https://api.github.com/users/dwhitena/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dwhitena/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 156
  },
  {
    "login": "extemporalgenome",
    "id": 536740,
    "avatar_url": "https://avatars1.githubusercontent.com/u/536740?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/extemporalgenome",
    "html_url": "https://github.com/extemporalgenome",
    "followers_url": "https://api.github.com/users/extemporalgenome/followers",
    "following_url": "https://api.github.com/users/extemporalgenome/following{/other_user}",
    "gists_url": "https://api.github.com/users/extemporalgenome/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/extemporalgenome/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/extemporalgenome/subscriptions",
    "organizations_url": "https://api.github.com/users/extemporalgenome/orgs",
    "repos_url": "https://api.github.com/users/extemporalgenome/repos",
    "events_url": "https://api.github.com/users/extemporalgenome/events{/privacy}",
    "received_events_url": "https://api.github.com/users/extemporalgenome/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 100
  },
  {
    "login": "jcbwlkr",
    "id": 2027263,
    "avatar_url": "https://avatars1.githubusercontent.com/u/2027263?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jcbwlkr",
    "html_url": "https://github.com/jcbwlkr",
    "followers_url": "https://api.github.com/users/jcbwlkr/followers",
    "following_url": "https://api.github.com/users/jcbwlkr/following{/other_user}",
    "gists_url": "https://api.github.com/users/jcbwlkr/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jcbwlkr/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jcbwlkr/subscriptions",
    "organizations_url": "https://api.github.com/users/jcbwlkr/orgs",
    "repos_url": "https://api.github.com/users/jcbwlkr/repos",
    "events_url": "https://api.github.com/users/jcbwlkr/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jcbwlkr/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 74
  },
  {
    "login": "markbates",
    "id": 3528,
    "avatar_url": "https://avatars3.githubusercontent.com/u/3528?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/markbates",
    "html_url": "https://github.com/markbates",
    "followers_url": "https://api.github.com/users/markbates/followers",
    "following_url": "https://api.github.com/users/markbates/following{/other_user}",
    "gists_url": "https://api.github.com/users/markbates/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/markbates/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/markbates/subscriptions",
    "organizations_url": "https://api.github.com/users/markbates/orgs",
    "repos_url": "https://api.github.com/users/markbates/repos",
    "events_url": "https://api.github.com/users/markbates/events{/privacy}",
    "received_events_url": "https://api.github.com/users/markbates/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 15
  },
  {
    "login": "codegangsta",
    "id": 178316,
    "avatar_url": "https://avatars1.githubusercontent.com/u/178316?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/codegangsta",
    "html_url": "https://github.com/codegangsta",
    "followers_url": "https://api.github.com/users/codegangsta/followers",
    "following_url": "https://api.github.com/users/codegangsta/following{/other_user}",
    "gists_url": "https://api.github.com/users/codegangsta/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/codegangsta/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/codegangsta/subscriptions",
    "organizations_url": "https://api.github.com/users/codegangsta/orgs",
    "repos_url": "https://api.github.com/users/codegangsta/repos",
    "events_url": "https://api.github.com/users/codegangsta/events{/privacy}",
    "received_events_url": "https://api.github.com/users/codegangsta/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 14
  },
  {
    "login": "scottefein",
    "id": 594123,
    "avatar_url": "https://avatars1.githubusercontent.com/u/594123?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/scottefein",
    "html_url": "https://github.com/scottefein",
    "followers_url": "https://api.github.com/users/scottefein/followers",
    "following_url": "https://api.github.com/users/scottefein/following{/other_user}",
    "gists_url": "https://api.github.com/users/scottefein/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/scottefein/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/scottefein/subscriptions",
    "organizations_url": "https://api.github.com/users/scottefein/orgs",
    "repos_url": "https://api.github.com/users/scottefein/repos",
    "events_url": "https://api.github.com/users/scottefein/events{/privacy}",
    "received_events_url": "https://api.github.com/users/scottefein/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 8
  },
  {
    "login": "sbinet",
    "id": 1070920,
    "avatar_url": "https://avatars2.githubusercontent.com/u/1070920?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sbinet",
    "html_url": "https://github.com/sbinet",
    "followers_url": "https://api.github.com/users/sbinet/followers",
    "following_url": "https://api.github.com/users/sbinet/following{/other_user}",
    "gists_url": "https://api.github.com/users/sbinet/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sbinet/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sbinet/subscriptions",
    "organizations_url": "https://api.github.com/users/sbinet/orgs",
    "repos_url": "https://api.github.com/users/sbinet/repos",
    "events_url": "https://api.github.com/users/sbinet/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sbinet/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 8
  },
  {
    "login": "freeeve",
    "id": 882560,
    "avatar_url": "https://avatars0.githubusercontent.com/u/882560?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/freeeve",
    "html_url": "https://github.com/freeeve",
    "followers_url": "https://api.github.com/users/freeeve/followers",
    "following_url": "https://api.github.com/users/freeeve/following{/other_user}",
    "gists_url": "https://api.github.com/users/freeeve/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/freeeve/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/freeeve/subscriptions",
    "organizations_url": "https://api.github.com/users/freeeve/orgs",
    "repos_url": "https://api.github.com/users/freeeve/repos",
    "events_url": "https://api.github.com/users/freeeve/events{/privacy}",
    "received_events_url": "https://api.github.com/users/freeeve/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 6
  },
  {
    "login": "ryanfaerman",
    "id": 218121,
    "avatar_url": "https://avatars3.githubusercontent.com/u/218121?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ryanfaerman",
    "html_url": "https://github.com/ryanfaerman",
    "followers_url": "https://api.github.com/users/ryanfaerman/followers",
    "following_url": "https://api.github.com/users/ryanfaerman/following{/other_user}",
    "gists_url": "https://api.github.com/users/ryanfaerman/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ryanfaerman/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ryanfaerman/subscriptions",
    "organizations_url": "https://api.github.com/users/ryanfaerman/orgs",
    "repos_url": "https://api.github.com/users/ryanfaerman/repos",
    "events_url": "https://api.github.com/users/ryanfaerman/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ryanfaerman/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 6
  },
  {
    "login": "bsreera",
    "id": 4218828,
    "avatar_url": "https://avatars3.githubusercontent.com/u/4218828?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bsreera",
    "html_url": "https://github.com/bsreera",
    "followers_url": "https://api.github.com/users/bsreera/followers",
    "following_url": "https://api.github.com/users/bsreera/following{/other_user}",
    "gists_url": "https://api.github.com/users/bsreera/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bsreera/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bsreera/subscriptions",
    "organizations_url": "https://api.github.com/users/bsreera/orgs",
    "repos_url": "https://api.github.com/users/bsreera/repos",
    "events_url": "https://api.github.com/users/bsreera/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bsreera/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 6
  },
  {
    "login": "Dfenniak",
    "id": 4259190,
    "avatar_url": "https://avatars0.githubusercontent.com/u/4259190?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Dfenniak",
    "html_url": "https://github.com/Dfenniak",
    "followers_url": "https://api.github.com/users/Dfenniak/followers",
    "following_url": "https://api.github.com/users/Dfenniak/following{/other_user}",
    "gists_url": "https://api.github.com/users/Dfenniak/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Dfenniak/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Dfenniak/subscriptions",
    "organizations_url": "https://api.github.com/users/Dfenniak/orgs",
    "repos_url": "https://api.github.com/users/Dfenniak/repos",
    "events_url": "https://api.github.com/users/Dfenniak/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Dfenniak/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 5
  },
  {
    "login": "egonzo",
    "id": 1641719,
    "avatar_url": "https://avatars0.githubusercontent.com/u/1641719?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/egonzo",
    "html_url": "https://github.com/egonzo",
    "followers_url": "https://api.github.com/users/egonzo/followers",
    "following_url": "https://api.github.com/users/egonzo/following{/other_user}",
    "gists_url": "https://api.github.com/users/egonzo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/egonzo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/egonzo/subscriptions",
    "organizations_url": "https://api.github.com/users/egonzo/orgs",
    "repos_url": "https://api.github.com/users/egonzo/repos",
    "events_url": "https://api.github.com/users/egonzo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/egonzo/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 5
  },
  {
    "login": "corylanou",
    "id": 585100,
    "avatar_url": "https://avatars3.githubusercontent.com/u/585100?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/corylanou",
    "html_url": "https://github.com/corylanou",
    "followers_url": "https://api.github.com/users/corylanou/followers",
    "following_url": "https://api.github.com/users/corylanou/following{/other_user}",
    "gists_url": "https://api.github.com/users/corylanou/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/corylanou/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/corylanou/subscriptions",
    "organizations_url": "https://api.github.com/users/corylanou/orgs",
    "repos_url": "https://api.github.com/users/corylanou/repos",
    "events_url": "https://api.github.com/users/corylanou/events{/privacy}",
    "received_events_url": "https://api.github.com/users/corylanou/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 4
  },
  {
    "login": "lkysow",
    "id": 1034429,
    "avatar_url": "https://avatars1.githubusercontent.com/u/1034429?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/lkysow",
    "html_url": "https://github.com/lkysow",
    "followers_url": "https://api.github.com/users/lkysow/followers",
    "following_url": "https://api.github.com/users/lkysow/following{/other_user}",
    "gists_url": "https://api.github.com/users/lkysow/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/lkysow/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/lkysow/subscriptions",
    "organizations_url": "https://api.github.com/users/lkysow/orgs",
    "repos_url": "https://api.github.com/users/lkysow/repos",
    "events_url": "https://api.github.com/users/lkysow/events{/privacy}",
    "received_events_url": "https://api.github.com/users/lkysow/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 3
  },
  {
    "login": "mvanholsteijn",
    "id": 576619,
    "avatar_url": "https://avatars3.githubusercontent.com/u/576619?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mvanholsteijn",
    "html_url": "https://github.com/mvanholsteijn",
    "followers_url": "https://api.github.com/users/mvanholsteijn/followers",
    "following_url": "https://api.github.com/users/mvanholsteijn/following{/other_user}",
    "gists_url": "https://api.github.com/users/mvanholsteijn/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mvanholsteijn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mvanholsteijn/subscriptions",
    "organizations_url": "https://api.github.com/users/mvanholsteijn/orgs",
    "repos_url": "https://api.github.com/users/mvanholsteijn/repos",
    "events_url": "https://api.github.com/users/mvanholsteijn/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mvanholsteijn/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 3
  },
  {
    "login": "dayvson",
    "id": 59447,
    "avatar_url": "https://avatars3.githubusercontent.com/u/59447?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dayvson",
    "html_url": "https://github.com/dayvson",
    "followers_url": "https://api.github.com/users/dayvson/followers",
    "following_url": "https://api.github.com/users/dayvson/following{/other_user}",
    "gists_url": "https://api.github.com/users/dayvson/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dayvson/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dayvson/subscriptions",
    "organizations_url": "https://api.github.com/users/dayvson/orgs",
    "repos_url": "https://api.github.com/users/dayvson/repos",
    "events_url": "https://api.github.com/users/dayvson/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dayvson/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 3
  },
  {
    "login": "danicat",
    "id": 5531172,
    "avatar_url": "https://avatars2.githubusercontent.com/u/5531172?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/danicat",
    "html_url": "https://github.com/danicat",
    "followers_url": "https://api.github.com/users/danicat/followers",
    "following_url": "https://api.github.com/users/danicat/following{/other_user}",
    "gists_url": "https://api.github.com/users/danicat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/danicat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/danicat/subscriptions",
    "organizations_url": "https://api.github.com/users/danicat/orgs",
    "repos_url": "https://api.github.com/users/danicat/repos",
    "events_url": "https://api.github.com/users/danicat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/danicat/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 3
  },
  {
    "login": "aarongreenlee",
    "id": 264508,
    "avatar_url": "https://avatars0.githubusercontent.com/u/264508?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aarongreenlee",
    "html_url": "https://github.com/aarongreenlee",
    "followers_url": "https://api.github.com/users/aarongreenlee/followers",
    "following_url": "https://api.github.com/users/aarongreenlee/following{/other_user}",
    "gists_url": "https://api.github.com/users/aarongreenlee/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aarongreenlee/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aarongreenlee/subscriptions",
    "organizations_url": "https://api.github.com/users/aarongreenlee/orgs",
    "repos_url": "https://api.github.com/users/aarongreenlee/repos",
    "events_url": "https://api.github.com/users/aarongreenlee/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aarongreenlee/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "AlexeyKupershtokh",
    "id": 499778,
    "avatar_url": "https://avatars2.githubusercontent.com/u/499778?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/AlexeyKupershtokh",
    "html_url": "https://github.com/AlexeyKupershtokh",
    "followers_url": "https://api.github.com/users/AlexeyKupershtokh/followers",
    "following_url": "https://api.github.com/users/AlexeyKupershtokh/following{/other_user}",
    "gists_url": "https://api.github.com/users/AlexeyKupershtokh/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/AlexeyKupershtokh/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/AlexeyKupershtokh/subscriptions",
    "organizations_url": "https://api.github.com/users/AlexeyKupershtokh/orgs",
    "repos_url": "https://api.github.com/users/AlexeyKupershtokh/repos",
    "events_url": "https://api.github.com/users/AlexeyKupershtokh/events{/privacy}",
    "received_events_url": "https://api.github.com/users/AlexeyKupershtokh/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "amankapoor",
    "id": 8210816,
    "avatar_url": "https://avatars2.githubusercontent.com/u/8210816?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/amankapoor",
    "html_url": "https://github.com/amankapoor",
    "followers_url": "https://api.github.com/users/amankapoor/followers",
    "following_url": "https://api.github.com/users/amankapoor/following{/other_user}",
    "gists_url": "https://api.github.com/users/amankapoor/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/amankapoor/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/amankapoor/subscriptions",
    "organizations_url": "https://api.github.com/users/amankapoor/orgs",
    "repos_url": "https://api.github.com/users/amankapoor/repos",
    "events_url": "https://api.github.com/users/amankapoor/events{/privacy}",
    "received_events_url": "https://api.github.com/users/amankapoor/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "LipGlossary",
    "id": 1580086,
    "avatar_url": "https://avatars2.githubusercontent.com/u/1580086?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/LipGlossary",
    "html_url": "https://github.com/LipGlossary",
    "followers_url": "https://api.github.com/users/LipGlossary/followers",
    "following_url": "https://api.github.com/users/LipGlossary/following{/other_user}",
    "gists_url": "https://api.github.com/users/LipGlossary/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/LipGlossary/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/LipGlossary/subscriptions",
    "organizations_url": "https://api.github.com/users/LipGlossary/orgs",
    "repos_url": "https://api.github.com/users/LipGlossary/repos",
    "events_url": "https://api.github.com/users/LipGlossary/events{/privacy}",
    "received_events_url": "https://api.github.com/users/LipGlossary/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "selva-oscura",
    "id": 4088970,
    "avatar_url": "https://avatars3.githubusercontent.com/u/4088970?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/selva-oscura",
    "html_url": "https://github.com/selva-oscura",
    "followers_url": "https://api.github.com/users/selva-oscura/followers",
    "following_url": "https://api.github.com/users/selva-oscura/following{/other_user}",
    "gists_url": "https://api.github.com/users/selva-oscura/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/selva-oscura/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/selva-oscura/subscriptions",
    "organizations_url": "https://api.github.com/users/selva-oscura/orgs",
    "repos_url": "https://api.github.com/users/selva-oscura/repos",
    "events_url": "https://api.github.com/users/selva-oscura/events{/privacy}",
    "received_events_url": "https://api.github.com/users/selva-oscura/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "DDRBoxman",
    "id": 207897,
    "avatar_url": "https://avatars0.githubusercontent.com/u/207897?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/DDRBoxman",
    "html_url": "https://github.com/DDRBoxman",
    "followers_url": "https://api.github.com/users/DDRBoxman/followers",
    "following_url": "https://api.github.com/users/DDRBoxman/following{/other_user}",
    "gists_url": "https://api.github.com/users/DDRBoxman/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/DDRBoxman/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/DDRBoxman/subscriptions",
    "organizations_url": "https://api.github.com/users/DDRBoxman/orgs",
    "repos_url": "https://api.github.com/users/DDRBoxman/repos",
    "events_url": "https://api.github.com/users/DDRBoxman/events{/privacy}",
    "received_events_url": "https://api.github.com/users/DDRBoxman/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "diwant",
    "id": 521869,
    "avatar_url": "https://avatars0.githubusercontent.com/u/521869?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/diwant",
    "html_url": "https://github.com/diwant",
    "followers_url": "https://api.github.com/users/diwant/followers",
    "following_url": "https://api.github.com/users/diwant/following{/other_user}",
    "gists_url": "https://api.github.com/users/diwant/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/diwant/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/diwant/subscriptions",
    "organizations_url": "https://api.github.com/users/diwant/orgs",
    "repos_url": "https://api.github.com/users/diwant/repos",
    "events_url": "https://api.github.com/users/diwant/events{/privacy}",
    "received_events_url": "https://api.github.com/users/diwant/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "ibjhb",
    "id": 265779,
    "avatar_url": "https://avatars3.githubusercontent.com/u/265779?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ibjhb",
    "html_url": "https://github.com/ibjhb",
    "followers_url": "https://api.github.com/users/ibjhb/followers",
    "following_url": "https://api.github.com/users/ibjhb/following{/other_user}",
    "gists_url": "https://api.github.com/users/ibjhb/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ibjhb/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ibjhb/subscriptions",
    "organizations_url": "https://api.github.com/users/ibjhb/orgs",
    "repos_url": "https://api.github.com/users/ibjhb/repos",
    "events_url": "https://api.github.com/users/ibjhb/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ibjhb/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "nathany",
    "id": 4566,
    "avatar_url": "https://avatars1.githubusercontent.com/u/4566?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nathany",
    "html_url": "https://github.com/nathany",
    "followers_url": "https://api.github.com/users/nathany/followers",
    "following_url": "https://api.github.com/users/nathany/following{/other_user}",
    "gists_url": "https://api.github.com/users/nathany/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nathany/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nathany/subscriptions",
    "organizations_url": "https://api.github.com/users/nathany/orgs",
    "repos_url": "https://api.github.com/users/nathany/repos",
    "events_url": "https://api.github.com/users/nathany/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nathany/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "vaskoz",
    "id": 21339,
    "avatar_url": "https://avatars0.githubusercontent.com/u/21339?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vaskoz",
    "html_url": "https://github.com/vaskoz",
    "followers_url": "https://api.github.com/users/vaskoz/followers",
    "following_url": "https://api.github.com/users/vaskoz/following{/other_user}",
    "gists_url": "https://api.github.com/users/vaskoz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vaskoz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vaskoz/subscriptions",
    "organizations_url": "https://api.github.com/users/vaskoz/orgs",
    "repos_url": "https://api.github.com/users/vaskoz/repos",
    "events_url": "https://api.github.com/users/vaskoz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vaskoz/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "williamhanisch",
    "id": 13632991,
    "avatar_url": "https://avatars2.githubusercontent.com/u/13632991?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/williamhanisch",
    "html_url": "https://github.com/williamhanisch",
    "followers_url": "https://api.github.com/users/williamhanisch/followers",
    "following_url": "https://api.github.com/users/williamhanisch/following{/other_user}",
    "gists_url": "https://api.github.com/users/williamhanisch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/williamhanisch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/williamhanisch/subscriptions",
    "organizations_url": "https://api.github.com/users/williamhanisch/orgs",
    "repos_url": "https://api.github.com/users/williamhanisch/repos",
    "events_url": "https://api.github.com/users/williamhanisch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/williamhanisch/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "forevermatt",
    "id": 6233204,
    "avatar_url": "https://avatars2.githubusercontent.com/u/6233204?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/forevermatt",
    "html_url": "https://github.com/forevermatt",
    "followers_url": "https://api.github.com/users/forevermatt/followers",
    "following_url": "https://api.github.com/users/forevermatt/following{/other_user}",
    "gists_url": "https://api.github.com/users/forevermatt/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/forevermatt/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/forevermatt/subscriptions",
    "organizations_url": "https://api.github.com/users/forevermatt/orgs",
    "repos_url": "https://api.github.com/users/forevermatt/repos",
    "events_url": "https://api.github.com/users/forevermatt/events{/privacy}",
    "received_events_url": "https://api.github.com/users/forevermatt/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  }
]`

const goContributors = `[
  {
    "login": "rsc",
    "id": 104030,
    "avatar_url": "https://avatars1.githubusercontent.com/u/104030?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rsc",
    "html_url": "https://github.com/rsc",
    "followers_url": "https://api.github.com/users/rsc/followers",
    "following_url": "https://api.github.com/users/rsc/following{/other_user}",
    "gists_url": "https://api.github.com/users/rsc/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rsc/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rsc/subscriptions",
    "organizations_url": "https://api.github.com/users/rsc/orgs",
    "repos_url": "https://api.github.com/users/rsc/repos",
    "events_url": "https://api.github.com/users/rsc/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rsc/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 6253
  },
  {
    "login": "griesemer",
    "id": 8528975,
    "avatar_url": "https://avatars2.githubusercontent.com/u/8528975?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/griesemer",
    "html_url": "https://github.com/griesemer",
    "followers_url": "https://api.github.com/users/griesemer/followers",
    "following_url": "https://api.github.com/users/griesemer/following{/other_user}",
    "gists_url": "https://api.github.com/users/griesemer/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/griesemer/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/griesemer/subscriptions",
    "organizations_url": "https://api.github.com/users/griesemer/orgs",
    "repos_url": "https://api.github.com/users/griesemer/repos",
    "events_url": "https://api.github.com/users/griesemer/events{/privacy}",
    "received_events_url": "https://api.github.com/users/griesemer/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2955
  },
  {
    "login": "robpike",
    "id": 4324516,
    "avatar_url": "https://avatars0.githubusercontent.com/u/4324516?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/robpike",
    "html_url": "https://github.com/robpike",
    "followers_url": "https://api.github.com/users/robpike/followers",
    "following_url": "https://api.github.com/users/robpike/following{/other_user}",
    "gists_url": "https://api.github.com/users/robpike/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/robpike/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/robpike/subscriptions",
    "organizations_url": "https://api.github.com/users/robpike/orgs",
    "repos_url": "https://api.github.com/users/robpike/repos",
    "events_url": "https://api.github.com/users/robpike/events{/privacy}",
    "received_events_url": "https://api.github.com/users/robpike/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2918
  },
  {
    "login": "bradfitz",
    "id": 2621,
    "avatar_url": "https://avatars1.githubusercontent.com/u/2621?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bradfitz",
    "html_url": "https://github.com/bradfitz",
    "followers_url": "https://api.github.com/users/bradfitz/followers",
    "following_url": "https://api.github.com/users/bradfitz/following{/other_user}",
    "gists_url": "https://api.github.com/users/bradfitz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bradfitz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bradfitz/subscriptions",
    "organizations_url": "https://api.github.com/users/bradfitz/orgs",
    "repos_url": "https://api.github.com/users/bradfitz/repos",
    "events_url": "https://api.github.com/users/bradfitz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bradfitz/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2080
  },
  {
    "login": "ianlancetaylor",
    "id": 3194333,
    "avatar_url": "https://avatars2.githubusercontent.com/u/3194333?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ianlancetaylor",
    "html_url": "https://github.com/ianlancetaylor",
    "followers_url": "https://api.github.com/users/ianlancetaylor/followers",
    "following_url": "https://api.github.com/users/ianlancetaylor/following{/other_user}",
    "gists_url": "https://api.github.com/users/ianlancetaylor/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ianlancetaylor/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ianlancetaylor/subscriptions",
    "organizations_url": "https://api.github.com/users/ianlancetaylor/orgs",
    "repos_url": "https://api.github.com/users/ianlancetaylor/repos",
    "events_url": "https://api.github.com/users/ianlancetaylor/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ianlancetaylor/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 1479
  },
  {
    "login": "adg",
    "id": 8446613,
    "avatar_url": "https://avatars0.githubusercontent.com/u/8446613?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/adg",
    "html_url": "https://github.com/adg",
    "followers_url": "https://api.github.com/users/adg/followers",
    "following_url": "https://api.github.com/users/adg/following{/other_user}",
    "gists_url": "https://api.github.com/users/adg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/adg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/adg/subscriptions",
    "organizations_url": "https://api.github.com/users/adg/orgs",
    "repos_url": "https://api.github.com/users/adg/repos",
    "events_url": "https://api.github.com/users/adg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/adg/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 1184
  },
  {
    "login": "josharian",
    "id": 67496,
    "avatar_url": "https://avatars2.githubusercontent.com/u/67496?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/josharian",
    "html_url": "https://github.com/josharian",
    "followers_url": "https://api.github.com/users/josharian/followers",
    "following_url": "https://api.github.com/users/josharian/following{/other_user}",
    "gists_url": "https://api.github.com/users/josharian/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/josharian/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/josharian/subscriptions",
    "organizations_url": "https://api.github.com/users/josharian/orgs",
    "repos_url": "https://api.github.com/users/josharian/repos",
    "events_url": "https://api.github.com/users/josharian/events{/privacy}",
    "received_events_url": "https://api.github.com/users/josharian/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 1116
  },
  {
    "login": "aclements",
    "id": 2688315,
    "avatar_url": "https://avatars0.githubusercontent.com/u/2688315?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aclements",
    "html_url": "https://github.com/aclements",
    "followers_url": "https://api.github.com/users/aclements/followers",
    "following_url": "https://api.github.com/users/aclements/following{/other_user}",
    "gists_url": "https://api.github.com/users/aclements/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aclements/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aclements/subscriptions",
    "organizations_url": "https://api.github.com/users/aclements/orgs",
    "repos_url": "https://api.github.com/users/aclements/repos",
    "events_url": "https://api.github.com/users/aclements/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aclements/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 1098
  },
  {
    "login": "minux",
    "id": 135652,
    "avatar_url": "https://avatars1.githubusercontent.com/u/135652?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/minux",
    "html_url": "https://github.com/minux",
    "followers_url": "https://api.github.com/users/minux/followers",
    "following_url": "https://api.github.com/users/minux/following{/other_user}",
    "gists_url": "https://api.github.com/users/minux/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/minux/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/minux/subscriptions",
    "organizations_url": "https://api.github.com/users/minux/orgs",
    "repos_url": "https://api.github.com/users/minux/repos",
    "events_url": "https://api.github.com/users/minux/events{/privacy}",
    "received_events_url": "https://api.github.com/users/minux/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 919
  },
  {
    "login": "dvyukov",
    "id": 1095328,
    "avatar_url": "https://avatars3.githubusercontent.com/u/1095328?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dvyukov",
    "html_url": "https://github.com/dvyukov",
    "followers_url": "https://api.github.com/users/dvyukov/followers",
    "following_url": "https://api.github.com/users/dvyukov/following{/other_user}",
    "gists_url": "https://api.github.com/users/dvyukov/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dvyukov/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dvyukov/subscriptions",
    "organizations_url": "https://api.github.com/users/dvyukov/orgs",
    "repos_url": "https://api.github.com/users/dvyukov/repos",
    "events_url": "https://api.github.com/users/dvyukov/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dvyukov/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 865
  },
  {
    "login": "randall77",
    "id": 6889504,
    "avatar_url": "https://avatars0.githubusercontent.com/u/6889504?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/randall77",
    "html_url": "https://github.com/randall77",
    "followers_url": "https://api.github.com/users/randall77/followers",
    "following_url": "https://api.github.com/users/randall77/following{/other_user}",
    "gists_url": "https://api.github.com/users/randall77/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/randall77/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/randall77/subscriptions",
    "organizations_url": "https://api.github.com/users/randall77/orgs",
    "repos_url": "https://api.github.com/users/randall77/repos",
    "events_url": "https://api.github.com/users/randall77/events{/privacy}",
    "received_events_url": "https://api.github.com/users/randall77/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 820
  },
  {
    "login": "mikioh",
    "id": 92117,
    "avatar_url": "https://avatars1.githubusercontent.com/u/92117?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mikioh",
    "html_url": "https://github.com/mikioh",
    "followers_url": "https://api.github.com/users/mikioh/followers",
    "following_url": "https://api.github.com/users/mikioh/following{/other_user}",
    "gists_url": "https://api.github.com/users/mikioh/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mikioh/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mikioh/subscriptions",
    "organizations_url": "https://api.github.com/users/mikioh/orgs",
    "repos_url": "https://api.github.com/users/mikioh/repos",
    "events_url": "https://api.github.com/users/mikioh/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mikioh/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 736
  },
  {
    "login": "alexbrainman",
    "id": 9796621,
    "avatar_url": "https://avatars2.githubusercontent.com/u/9796621?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/alexbrainman",
    "html_url": "https://github.com/alexbrainman",
    "followers_url": "https://api.github.com/users/alexbrainman/followers",
    "following_url": "https://api.github.com/users/alexbrainman/following{/other_user}",
    "gists_url": "https://api.github.com/users/alexbrainman/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/alexbrainman/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/alexbrainman/subscriptions",
    "organizations_url": "https://api.github.com/users/alexbrainman/orgs",
    "repos_url": "https://api.github.com/users/alexbrainman/repos",
    "events_url": "https://api.github.com/users/alexbrainman/events{/privacy}",
    "received_events_url": "https://api.github.com/users/alexbrainman/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 715
  },
  {
    "login": "mdempsky",
    "id": 38349,
    "avatar_url": "https://avatars0.githubusercontent.com/u/38349?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mdempsky",
    "html_url": "https://github.com/mdempsky",
    "followers_url": "https://api.github.com/users/mdempsky/followers",
    "following_url": "https://api.github.com/users/mdempsky/following{/other_user}",
    "gists_url": "https://api.github.com/users/mdempsky/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mdempsky/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mdempsky/subscriptions",
    "organizations_url": "https://api.github.com/users/mdempsky/orgs",
    "repos_url": "https://api.github.com/users/mdempsky/repos",
    "events_url": "https://api.github.com/users/mdempsky/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mdempsky/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 664
  },
  {
    "login": "agl",
    "id": 21203,
    "avatar_url": "https://avatars3.githubusercontent.com/u/21203?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/agl",
    "html_url": "https://github.com/agl",
    "followers_url": "https://api.github.com/users/agl/followers",
    "following_url": "https://api.github.com/users/agl/following{/other_user}",
    "gists_url": "https://api.github.com/users/agl/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/agl/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/agl/subscriptions",
    "organizations_url": "https://api.github.com/users/agl/orgs",
    "repos_url": "https://api.github.com/users/agl/repos",
    "events_url": "https://api.github.com/users/agl/events{/privacy}",
    "received_events_url": "https://api.github.com/users/agl/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 522
  },
  {
    "login": "ken",
    "id": 9967170,
    "avatar_url": "https://avatars3.githubusercontent.com/u/9967170?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ken",
    "html_url": "https://github.com/ken",
    "followers_url": "https://api.github.com/users/ken/followers",
    "following_url": "https://api.github.com/users/ken/following{/other_user}",
    "gists_url": "https://api.github.com/users/ken/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ken/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ken/subscriptions",
    "organizations_url": "https://api.github.com/users/ken/orgs",
    "repos_url": "https://api.github.com/users/ken/repos",
    "events_url": "https://api.github.com/users/ken/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ken/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 508
  },
  {
    "login": "davecheney",
    "id": 7171,
    "avatar_url": "https://avatars0.githubusercontent.com/u/7171?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/davecheney",
    "html_url": "https://github.com/davecheney",
    "followers_url": "https://api.github.com/users/davecheney/followers",
    "following_url": "https://api.github.com/users/davecheney/following{/other_user}",
    "gists_url": "https://api.github.com/users/davecheney/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/davecheney/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/davecheney/subscriptions",
    "organizations_url": "https://api.github.com/users/davecheney/orgs",
    "repos_url": "https://api.github.com/users/davecheney/repos",
    "events_url": "https://api.github.com/users/davecheney/events{/privacy}",
    "received_events_url": "https://api.github.com/users/davecheney/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 476
  },
  {
    "login": "nigeltao",
    "id": 8565232,
    "avatar_url": "https://avatars3.githubusercontent.com/u/8565232?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nigeltao",
    "html_url": "https://github.com/nigeltao",
    "followers_url": "https://api.github.com/users/nigeltao/followers",
    "following_url": "https://api.github.com/users/nigeltao/following{/other_user}",
    "gists_url": "https://api.github.com/users/nigeltao/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nigeltao/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nigeltao/subscriptions",
    "organizations_url": "https://api.github.com/users/nigeltao/orgs",
    "repos_url": "https://api.github.com/users/nigeltao/repos",
    "events_url": "https://api.github.com/users/nigeltao/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nigeltao/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 436
  },
  {
    "login": "crawshaw",
    "id": 161319,
    "avatar_url": "https://avatars0.githubusercontent.com/u/161319?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/crawshaw",
    "html_url": "https://github.com/crawshaw",
    "followers_url": "https://api.github.com/users/crawshaw/followers",
    "following_url": "https://api.github.com/users/crawshaw/following{/other_user}",
    "gists_url": "https://api.github.com/users/crawshaw/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/crawshaw/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/crawshaw/subscriptions",
    "organizations_url": "https://api.github.com/users/crawshaw/orgs",
    "repos_url": "https://api.github.com/users/crawshaw/repos",
    "events_url": "https://api.github.com/users/crawshaw/events{/privacy}",
    "received_events_url": "https://api.github.com/users/crawshaw/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 391
  },
  {
    "login": "dsymonds",
    "id": 31506,
    "avatar_url": "https://avatars2.githubusercontent.com/u/31506?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dsymonds",
    "html_url": "https://github.com/dsymonds",
    "followers_url": "https://api.github.com/users/dsymonds/followers",
    "following_url": "https://api.github.com/users/dsymonds/following{/other_user}",
    "gists_url": "https://api.github.com/users/dsymonds/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dsymonds/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dsymonds/subscriptions",
    "organizations_url": "https://api.github.com/users/dsymonds/orgs",
    "repos_url": "https://api.github.com/users/dsymonds/repos",
    "events_url": "https://api.github.com/users/dsymonds/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dsymonds/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 348
  },
  {
    "login": "remyoudompheng",
    "id": 175246,
    "avatar_url": "https://avatars3.githubusercontent.com/u/175246?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/remyoudompheng",
    "html_url": "https://github.com/remyoudompheng",
    "followers_url": "https://api.github.com/users/remyoudompheng/followers",
    "following_url": "https://api.github.com/users/remyoudompheng/following{/other_user}",
    "gists_url": "https://api.github.com/users/remyoudompheng/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/remyoudompheng/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/remyoudompheng/subscriptions",
    "organizations_url": "https://api.github.com/users/remyoudompheng/orgs",
    "repos_url": "https://api.github.com/users/remyoudompheng/repos",
    "events_url": "https://api.github.com/users/remyoudompheng/events{/privacy}",
    "received_events_url": "https://api.github.com/users/remyoudompheng/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 323
  },
  {
    "login": "cherrymui",
    "id": 14119929,
    "avatar_url": "https://avatars2.githubusercontent.com/u/14119929?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cherrymui",
    "html_url": "https://github.com/cherrymui",
    "followers_url": "https://api.github.com/users/cherrymui/followers",
    "following_url": "https://api.github.com/users/cherrymui/following{/other_user}",
    "gists_url": "https://api.github.com/users/cherrymui/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cherrymui/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cherrymui/subscriptions",
    "organizations_url": "https://api.github.com/users/cherrymui/orgs",
    "repos_url": "https://api.github.com/users/cherrymui/repos",
    "events_url": "https://api.github.com/users/cherrymui/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cherrymui/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 261
  },
  {
    "login": "mwhudson",
    "id": 672022,
    "avatar_url": "https://avatars3.githubusercontent.com/u/672022?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mwhudson",
    "html_url": "https://github.com/mwhudson",
    "followers_url": "https://api.github.com/users/mwhudson/followers",
    "following_url": "https://api.github.com/users/mwhudson/following{/other_user}",
    "gists_url": "https://api.github.com/users/mwhudson/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mwhudson/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mwhudson/subscriptions",
    "organizations_url": "https://api.github.com/users/mwhudson/orgs",
    "repos_url": "https://api.github.com/users/mwhudson/repos",
    "events_url": "https://api.github.com/users/mwhudson/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mwhudson/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 258
  },
  {
    "login": "0intro",
    "id": 6043744,
    "avatar_url": "https://avatars3.githubusercontent.com/u/6043744?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/0intro",
    "html_url": "https://github.com/0intro",
    "followers_url": "https://api.github.com/users/0intro/followers",
    "following_url": "https://api.github.com/users/0intro/following{/other_user}",
    "gists_url": "https://api.github.com/users/0intro/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/0intro/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/0intro/subscriptions",
    "organizations_url": "https://api.github.com/users/0intro/orgs",
    "repos_url": "https://api.github.com/users/0intro/repos",
    "events_url": "https://api.github.com/users/0intro/events{/privacy}",
    "received_events_url": "https://api.github.com/users/0intro/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 203
  },
  {
    "login": "dsnet",
    "id": 6354026,
    "avatar_url": "https://avatars1.githubusercontent.com/u/6354026?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dsnet",
    "html_url": "https://github.com/dsnet",
    "followers_url": "https://api.github.com/users/dsnet/followers",
    "following_url": "https://api.github.com/users/dsnet/following{/other_user}",
    "gists_url": "https://api.github.com/users/dsnet/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dsnet/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dsnet/subscriptions",
    "organizations_url": "https://api.github.com/users/dsnet/orgs",
    "repos_url": "https://api.github.com/users/dsnet/repos",
    "events_url": "https://api.github.com/users/dsnet/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dsnet/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 199
  },
  {
    "login": "mundaym",
    "id": 15000766,
    "avatar_url": "https://avatars2.githubusercontent.com/u/15000766?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mundaym",
    "html_url": "https://github.com/mundaym",
    "followers_url": "https://api.github.com/users/mundaym/followers",
    "following_url": "https://api.github.com/users/mundaym/following{/other_user}",
    "gists_url": "https://api.github.com/users/mundaym/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mundaym/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mundaym/subscriptions",
    "organizations_url": "https://api.github.com/users/mundaym/orgs",
    "repos_url": "https://api.github.com/users/mundaym/repos",
    "events_url": "https://api.github.com/users/mundaym/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mundaym/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 197
  },
  {
    "login": "ALTree",
    "id": 3586803,
    "avatar_url": "https://avatars2.githubusercontent.com/u/3586803?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ALTree",
    "html_url": "https://github.com/ALTree",
    "followers_url": "https://api.github.com/users/ALTree/followers",
    "following_url": "https://api.github.com/users/ALTree/following{/other_user}",
    "gists_url": "https://api.github.com/users/ALTree/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ALTree/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ALTree/subscriptions",
    "organizations_url": "https://api.github.com/users/ALTree/orgs",
    "repos_url": "https://api.github.com/users/ALTree/repos",
    "events_url": "https://api.github.com/users/ALTree/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ALTree/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 189
  },
  {
    "login": "martisch",
    "id": 184995,
    "avatar_url": "https://avatars0.githubusercontent.com/u/184995?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/martisch",
    "html_url": "https://github.com/martisch",
    "followers_url": "https://api.github.com/users/martisch/followers",
    "following_url": "https://api.github.com/users/martisch/following{/other_user}",
    "gists_url": "https://api.github.com/users/martisch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/martisch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/martisch/subscriptions",
    "organizations_url": "https://api.github.com/users/martisch/orgs",
    "repos_url": "https://api.github.com/users/martisch/repos",
    "events_url": "https://api.github.com/users/martisch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/martisch/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 182
  },
  {
    "login": "mvdan",
    "id": 3576549,
    "avatar_url": "https://avatars0.githubusercontent.com/u/3576549?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mvdan",
    "html_url": "https://github.com/mvdan",
    "followers_url": "https://api.github.com/users/mvdan/followers",
    "following_url": "https://api.github.com/users/mvdan/following{/other_user}",
    "gists_url": "https://api.github.com/users/mvdan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mvdan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mvdan/subscriptions",
    "organizations_url": "https://api.github.com/users/mvdan/orgs",
    "repos_url": "https://api.github.com/users/mvdan/repos",
    "events_url": "https://api.github.com/users/mvdan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mvdan/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 172
  },
  {
    "login": "dr2chase",
    "id": 1928999,
    "avatar_url": "https://avatars0.githubusercontent.com/u/1928999?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dr2chase",
    "html_url": "https://github.com/dr2chase",
    "followers_url": "https://api.github.com/users/dr2chase/followers",
    "following_url": "https://api.github.com/users/dr2chase/following{/other_user}",
    "gists_url": "https://api.github.com/users/dr2chase/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dr2chase/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dr2chase/subscriptions",
    "organizations_url": "https://api.github.com/users/dr2chase/orgs",
    "repos_url": "https://api.github.com/users/dr2chase/repos",
    "events_url": "https://api.github.com/users/dr2chase/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dr2chase/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 166
  }
]`
