# Build the Go Binary.
FROM golang:1.11.4 as build
ENV CGO_ENABLED 0
ARG VCS_REF
ARG PACKAGE_NAME
ARG PACKAGE_PREFIX
RUN mkdir -p /go/src/github.com/ardanlabs/gotraining/topics/go/profiling/project
COPY . /go/src/github.com/ardanlabs/gotraining/topics/go/profiling/project
WORKDIR /go/src/github.com/ardanlabs/gotraining/topics/go/profiling/project
RUN go build -a -tags netgo

# Run the Go Binary in Alpine.
FROM alpine:3.7
ARG BUILD_DATE
ARG VCS_REF
ARG PACKAGE_NAME
ARG PACKAGE_PREFIX
COPY --from=build /go/src/github.com/ardanlabs/gotraining/topics/go/profiling/project/project /app/main
COPY --from=build /go/src/github.com/ardanlabs/gotraining/topics/go/profiling/project/views /app/views
COPY --from=build /go/src/github.com/ardanlabs/gotraining/topics/go/profiling/project/static /app/static
WORKDIR /app
CMD /app/main

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="${TITLE}" \
      org.opencontainers.image.authors="William Kennedy <bill@ardanlabs.com>" \
      org.opencontainers.image.source="https://github.com/ardanlabs/gotraining/topics/go/profiling/project" \
      org.opencontainers.image.revision="${VCS_REF}" \
      org.opencontainers.image.vendor="Ardan Labs"
